export const mockRaceData = [
  {
    advertised_start: {seconds: 1713705900},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: '697a1efc-2769-49e5-a820-6a9d44a2057d',
    meeting_name: 'Greyville',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Greyville","state":"SAF","country":"SAF","number":6,"race_name":"Tabgold Score 6 Score 8 Score 10 Mr 86 Handicap","time":"2024-04-21T13:25:00Z","class":"RBH86","start_type":"","prizemonies":{"1st":71880,"2nd":22997,"3rd":11510,"4th":5755,"5th":2866,"total_value":9357},"rail_position":"","track_direction":"Right","track_surface":"Turf","group":""}}',
      distance: 1600,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'PHUTULICIOUS (2) won a good race in his last start over 1400m at Scottsville. He lost a length leaving the start but quickened up well and won going away. He can follow up with another victory. WICCAN WARRIOR (6) ran on well when finishing third of 10 over 1400m last time. He has dropped to a competitive rating and with Gavin Lerena retaining the ride should be figuring in the finish. EL REY VIENE (9) has good recent form lines to his credit. He has won once and finished third twice from four starts on this course. Rachel Venniker is likely to use his early gate speed to overcome his wide draw of nine and he may prove hard to peg back. NINETY NINE HEROS (1) resumes from a spell having won his only start last prep over 1950m at Scottsville. Jumps from the inside gate and fresh-up should be fighting out the finish.',
      race_comment_alternative:
        'PHUTULICIOUS (2) won a good race in his last start over 1400m at Scottsville. He lost a length leaving the start but quickened up well and won going away. He can follow up with another victory. WICCAN WARRIOR (6) ran on well when finishing third of 10 over 1400m last time. He has dropped to a competitive rating and with Gavin Lerena retaining the ride should be figuring in the finish. EL REY VIENE (9) has good recent form lines to his credit. He has won once and finished third twice from four starts on this course. Rachel Venniker is likely to use his early gate speed to overcome his wide draw of nine and he may prove hard to peg back. NINETY NINE HEROS (1) resumes from a spell having won his only start last prep over 1950m at Scottsville. Jumps from the inside gate and fresh-up should be fighting out the finish.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
      weather: [Object],
      weather_id: '18c6f07a-b37b-11e7-aabe-061a47531548',
    },
    race_id: '255d9c42-8141-43e9-aa38-ad6356a3f08e',
    race_name: 'Tabgold Score 6 Score 8 Score 10 Mr 86 Handicap',
    race_number: 6,
    venue_country: 'SAF',
    venue_id: 'e2f2c9d6-2188-4d9d-9fe1-51f5ecc766d3',
    venue_name: 'Greyville',
    venue_state: 'SAF',
  },
  {
    advertised_start: {seconds: 1713706140},
    category_id: '9daef0d7-bf3c-4f50-921d-8e818c60fe61',
    meeting_id: '2a2711e3-b396-4fbb-94ae-b856a779c6a3',
    meeting_name: 'Hove Bags.',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Hove Bags.","state":"UK","country":"UK","number":3,"race_name":"Race 3","time":"2024-04-21T13:29:00Z","class":"A1","start_type":"","prizemonies":{"total_value":824},"rail_position":"","track_direction":"Right","track_surface":"All Weather","group":""}}',
      distance: 500,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'GOLDEN WINGS (6) has a strong overall record having nine wins and 18 places from 36 starts but was out of the money last time when sixth (30.99) over 515m at this track. Performs well off this trap. Expected to feature in the finish. BURROWS RUBY (3) has been in super consistent form, last time breaking from this same trap when second in an A1 at this track (29.96) and making it six straight placings. Has the ability and looks a key chance. MAIREADS LION (1) jumps from the inside trap. Latest effort finished 2nd over 500m at this track beaten 4 lengths (30.35) behind Lucky Sevens in an A1 on April 5. Can feature in the finish. DROOPYS RAMPANT (2) missed the placings here last start but is well-placed to make amends.',
      race_comment_alternative:
        'GOLDEN WINGS (6) has a strong overall record having nine wins and 18 places from 36 starts but was out of the money last time when sixth (30.99) over 515m at this track. Performs well off this trap. Expected to feature in the finish. BURROWS RUBY (3) has been in super consistent form, last time breaking from this same trap when second in an A1 at this track (29.96) and making it six straight placings. Has the ability and looks a key chance. MAIREADS LION (1) jumps from the inside trap. Latest effort finished 2nd over 500m at this track beaten 4 lengths (30.35) behind Lucky Sevens in an A1 on April 5. Can feature in the finish. DROOPYS RAMPANT (2) missed the placings here last start but is well-placed to make amends.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
    },
    race_id: '11407f2e-ec6a-4066-95c4-6a8755368eb2',
    race_name: 'Race 3',
    race_number: 3,
    venue_country: 'UK',
    venue_id: '217ca030-7d7b-4845-85c5-ff2fd36def7b',
    venue_name: 'Hove Bags.',
    venue_state: 'UK',
  },
  {
    advertised_start: {seconds: 1713706200},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: '22c82496-f005-4f73-91ed-5883d28e05c0',
    meeting_name: 'Milan',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Milan","state":"ITA","country":"ITA","number":1,"race_name":"Premio Tattersalls Ireland Fairyhouse","time":"2024-04-21T13:30:00Z","class":"3Y MDN","start_type":"","prizemonies":null,"rail_position":"","track_direction":"","track_surface":"","group":""}}',
      distance: 2200,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
      weather: [Object],
      weather_id: '08e5f78c-1a36-11eb-9269-cef03e67f1a3',
    },
    race_id: '3340e124-21f8-4a85-be9a-5df02ab67311',
    race_name: 'Premio Tattersalls Ireland Fairyhouse',
    race_number: 1,
    venue_country: 'ITA',
    venue_id: 'f3148c21-aa15-47a3-9648-aa0fd7ef028e',
    venue_name: 'Milan',
    venue_state: 'ITA',
  },
  {
    advertised_start: {seconds: 1713706200},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: '830a7d7f-c708-4f68-ac57-27be7548e7af',
    meeting_name: 'Koln',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Koln","state":"DEU","country":"DEU","number":4,"race_name":"1M Stakes","time":"2024-04-21T13:30:00Z","class":"OPEN (A)","start_type":"","prizemonies":{"total_value":115894},"rail_position":"","track_direction":"Right","track_surface":"Turf","group":""}}',
      distance: 1600,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'ANALYTICS (1) debuted with a 2.25L victory over 1600m at Leipzig. Taken to follow up for a top yard. QUETAME (3) impressed when winning by 3L in a 1700m contest at Krefeld in November. Expected to play a part in the finish. LADY MARY (2) suffered a head defeat when runner-up in the G2 Preis Der WInterkonigin over 1600m at Baden-Baden in October. Danger to all. QUEUES LIKELY (4) won by 1.25L in a 1441m handicap at Wolverhampton. Shortlisted on her return to turf.',
      race_comment_alternative:
        'ANALYTICS (1) debuted with a 2.25L victory over 1600m at Leipzig. Taken to follow up for a top yard. QUETAME (3) impressed when winning by 3L in a 1700m contest at Krefeld in November. Expected to play a part in the finish. LADY MARY (2) suffered a head defeat when runner-up in the G2 Preis Der WInterkonigin over 1600m at Baden-Baden in October. Danger to all. QUEUES LIKELY (4) won by 1.25L in a 1441m handicap at Wolverhampton. Shortlisted on her return to turf.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
      weather: [Object],
      weather_id: '5ba75165-3cec-11eb-88bb-36fbfdf5d97f',
    },
    race_id: '391b8f24-c345-4bf4-9dc5-fb1730d366d0',
    race_name: '1M Stakes',
    race_number: 4,
    venue_country: 'DEU',
    venue_id: '48d9e7a0-7dee-4e31-911e-973c72e2e4b3',
    venue_name: 'Koln',
    venue_state: 'DEU',
  },
  {
    advertised_start: {seconds: 1713706320},
    category_id: '9daef0d7-bf3c-4f50-921d-8e818c60fe61',
    meeting_id: 'd3d6b629-a35f-4436-b4d3-226b1013574e',
    meeting_name: 'Doncaster Bags',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Doncaster Bags","state":"UK","country":"UK","number":11,"race_name":"275Mtrs (D3)","time":"2024-04-21T13:32:00Z","class":"D3","start_type":"","prizemonies":{"total_value":484},"rail_position":"","track_direction":"Right","track_surface":"All Weather","group":""}}',
      distance: 275,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'BATHAMS CLOUD (5) ran a good time (17.39) winning a D3 two back at this track but missed the frame latest finishing sixth at this track. Has the ability and expected to bounce back. MONEYHERE LAD (4) turned in a plain performance last time when fifth at this track over 275m behind Brynoffa Flissy (17.77) in a D3. Can do much better this time. LUNA JET (6) has a fair record and proved too classy last time to win by 0.8 lengths at this track in a handy 17.64 beating Jumeirah Meadow. One of the prime contenders. DRUMCROW YANK (3) has ability and finds the right scenario to bounce back.',
      race_comment_alternative:
        'BATHAMS CLOUD (5) ran a good time (17.39) winning a D3 two back at this track but missed the frame latest finishing sixth at this track. Has the ability and expected to bounce back. MONEYHERE LAD (4) turned in a plain performance last time when fifth at this track over 275m behind Brynoffa Flissy (17.77) in a D3. Can do much better this time. LUNA JET (6) has a fair record and proved too classy last time to win by 0.8 lengths at this track in a handy 17.64 beating Jumeirah Meadow. One of the prime contenders. DRUMCROW YANK (3) has ability and finds the right scenario to bounce back.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
    },
    race_id: 'f4abfa56-e815-4dcd-9300-66f218b03740',
    race_name: '275Mtrs (D3)',
    race_number: 11,
    venue_country: 'UK',
    venue_id: 'c4fb30d9-db2b-49c2-9a75-71e8b57a8aea',
    venue_name: 'Doncaster Bags',
    venue_state: 'UK',
  },
  {
    advertised_start: {seconds: 1713706320},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: '60c57a78-c767-4d19-917d-0b6440e015fe',
    meeting_name: 'Toulouse',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Toulouse","state":"FR","country":"FR","number":8,"race_name":"Handicap 4 Ans","time":"2024-04-21T13:32:00Z","class":"HCP CL4","start_type":"","prizemonies":{"total_value":29801},"rail_position":"","track_direction":"Right","track_surface":"Turf","group":""}}',
      distance: 1400,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'GAILLARD (4) ran a blinder when a close-up fourth in a 1200m Class Two handicap at Deauville eight months ago. The front two have scored subsequently to give the form some substance and he can get off the mark on his belated return to action. Recent Marseille-Vivaux AW winner BELL SONG (1) must be respected back in handicap company off a 2kg higher mark and PURPLE RAIN (9) has to be on the shortlist given he finished a good second off this rating in a Class Three at Marseille-Borely two back. IDAMANTE (2) cannot be discounted.',
      race_comment_alternative:
        'GAILLARD (4) ran a blinder when a close-up fourth in a 1200m Class Two handicap at Deauville eight months ago. The front two have scored subsequently to give the form some substance and he can get off the mark on his belated return to action. Recent Marseille-Vivaux AW winner BELL SONG (1) must be respected back in handicap company off a 2kg higher mark and PURPLE RAIN (9) has to be on the shortlist given he finished a good second off this rating in a Class Three at Marseille-Borely two back. IDAMANTE (2) cannot be discounted.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '906cd562-a37c-11e7-a5c6-0ab32e6ac8d2',
      weather: [Object],
      weather_id: 'e59d2021-a879-11e7-99a6-06918c628bb8',
    },
    race_id: '0afbaf02-12ac-4c42-a716-94ab4375d8bb',
    race_name: 'Handicap 4 Ans',
    race_number: 8,
    venue_country: 'FR',
    venue_id: '0a631c2a-71bf-4a5b-9f91-5ba55554c418',
    venue_name: 'Toulouse',
    venue_state: 'FR',
  },
  {
    advertised_start: {seconds: 1713706320},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: 'a3d736d9-0d84-4f91-81d4-0aa78207a95d',
    meeting_name: 'Wincanton',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Wincanton","state":"UK","country":"UK","number":3,"race_name":"Royal Bath And West Show Maiden Hurdle (Gbb Race) (Div 1)","time":"2024-04-21T13:32:00Z","class":"HDLE MDN, C4","start_type":"","prizemonies":{"total_value":13837},"rail_position":"True","track_direction":"Right","track_surface":"Turf","group":""}}',
      distance: 3063,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'BENY NAHAR ROAD (1) did well at Plumpton when a smart second in a 3200m maiden hurdle. The five-year-old has placed at this track previously and holds every chance. BOB BOB RICARD (2) brings solid placed form following a third over 4200m at Plumpton in January. Open to further progress and could go close again. MIRABAD (4) placed among Listed company last year in France. Showed promise on UK and hurdle debut when a decent fourth in a 3200m maiden hurdle at Wetherby during January. Looks one to note. THE LIKELY LAD (5) indicated ability in France and is worth a market check.',
      race_comment_alternative:
        'BENY NAHAR ROAD (1) did well at Plumpton when a smart second in a 3200m maiden hurdle. The five-year-old has placed at this track previously and holds every chance. BOB BOB RICARD (2) brings solid placed form following a third over 4200m at Plumpton in January. Open to further progress and could go close again. MIRABAD (4) placed among Listed company last year in France. Showed promise on UK and hurdle debut when a decent fourth in a 3200m maiden hurdle at Wetherby during January. Looks one to note. THE LIKELY LAD (5) indicated ability in France and is worth a market check.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
      weather: [Object],
      weather_id: '5ba75165-3cec-11eb-88bb-36fbfdf5d97f',
    },
    race_id: '6d590b33-6aef-4561-af9c-5ea10f5f3c29',
    race_name: 'Royal Bath And West Show Maiden Hurdle (Gbb Race) (Div 1)',
    race_number: 3,
    venue_country: 'UK',
    venue_id: 'fce2337c-9c00-41b0-8fa1-416b0f8a432d',
    venue_name: 'Wincanton',
    venue_state: 'UK',
  },
  {
    advertised_start: {seconds: 1713706740},
    category_id: '9daef0d7-bf3c-4f50-921d-8e818c60fe61',
    meeting_id: '5a91b335-8774-4e81-9ca1-bfa5b1cb869b',
    meeting_name: 'Sheffield Bags',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Sheffield Bags","state":"UK","country":"UK","number":3,"race_name":"Adopt A Greyhound @ Sheffield Retired Greyhounds","time":"2024-04-21T13:39:00Z","class":"D3","start_type":"","prizemonies":{"total_value":669},"rail_position":"","track_direction":"Right","track_surface":"All Weather","group":""}}',
      distance: 280,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'RUSSANDA LEXI (6) was below latest but prior to that a D3 winner in quick time (16.48) at this track in a D3. Expecting significant improvement this line-up. LA FLOR (3) made it back to back wins last time, scoring in a best of the card time (16.48) at this track. Some good form is emerging from her last run. Sure to be thereabouts. TREVILLA STAR (4) turned in a better effort at this track last start, finishing third behind Neverendingstory (29.77) in an A4. Bold showing expected. JACOBITE (5) looks well placed here following a D2 win two back before finishing sixth at his latest appearance in a D2 at this track over 280m (16.71). This easier and gets chance to atone.',
      race_comment_alternative:
        'RUSSANDA LEXI (6) was below latest but prior to that a D3 winner in quick time (16.48) at this track in a D3. Expecting significant improvement this line-up. LA FLOR (3) made it back to back wins last time, scoring in a best of the card time (16.48) at this track. Some good form is emerging from her last run. Sure to be thereabouts. TREVILLA STAR (4) turned in a better effort at this track last start, finishing third behind Neverendingstory (29.77) in an A4. Bold showing expected. JACOBITE (5) looks well placed here following a D2 win two back before finishing sixth at his latest appearance in a D2 at this track over 280m (16.71). This easier and gets chance to atone.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '10a14653-a33d-11e7-810d-0a1a4ae29bd2',
      weather: [Object],
      weather_id: '08e5f78c-1a36-11eb-9269-cef03e67f1a3',
    },
    race_id: 'aafd9b19-02ea-4534-a65f-06095fc01574',
    race_name: 'Adopt A Greyhound @ Sheffield Retired Greyhounds',
    race_number: 3,
    venue_country: 'UK',
    venue_id: '764e58a3-a0d2-4b09-b6a4-db218606f7d5',
    venue_name: 'Sheffield Bags',
    venue_state: 'UK',
  },
  {
    advertised_start: {seconds: 1713706800},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: '9b5777ef-4207-415c-aedc-9e52fe79a14b',
    meeting_name: 'Tramore',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Tramore","state":"IRE","country":"IRE","number":2,"race_name":"Irish Stallion Farms Ebf Mares Maiden Hurdle","time":"2024-04-21T13:40:00Z","class":"HDLE MDN","start_type":"","prizemonies":{"total_value":27675},"rail_position":"True","track_direction":"Right","track_surface":"Turf","group":""}}',
      distance: 3337,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      race_comment:
        'GROOVEYKINDOFLOVE (9) races for a leading jockey and trainer combination. Showed plenty of promise second up finishing second in a 3400m maiden hurdle at Down Royal. Leading contender. MAGIC DAWN (2) ran with credit at Naas when fifth tackling a field of nineteen in a 3200m mares maiden hurdle. May go close. PAMPAR LADY (11) placed third at Clonmel last November attempting a 3200m maiden hurdle. Could build on that effort after a break. RUSSELLSBELLE (12) is worth a market check upon return.',
      race_comment_alternative:
        'GROOVEYKINDOFLOVE (9) races for a leading jockey and trainer combination. Showed plenty of promise second up finishing second in a 3400m maiden hurdle at Down Royal. Leading contender. MAGIC DAWN (2) ran with credit at Naas when fifth tackling a field of nineteen in a 3200m mares maiden hurdle. May go close. PAMPAR LADY (11) placed third at Clonmel last November attempting a 3200m maiden hurdle. Could build on that effort after a break. RUSSELLSBELLE (12) is worth a market check upon return.',
      silk_base_url: 'drr38safykj6s.cloudfront.net',
      track_condition: [Object],
      track_condition_id: '906cd562-a37c-11e7-a5c6-0ab32e6ac8d2',
      weather: [Object],
      weather_id: '08e5f78c-1a36-11eb-9269-cef03e67f1a3',
    },
    race_id: '3a8cb158-f901-49aa-8720-b183b2052479',
    race_name: 'Irish Stallion Farms Ebf Mares Maiden Hurdle',
    race_number: 2,
    venue_country: 'IRE',
    venue_id: '1c7765bc-a1f5-416b-834d-71dde2bfbb49',
    venue_name: 'Tramore',
    venue_state: 'IRE',
  },
  {
    advertised_start: {seconds: 1713706800},
    category_id: '4a2788f8-e825-4d36-9894-efd4baf1cfae',
    meeting_id: 'a980b98b-1302-49b4-833e-bf7c594380cf',
    meeting_name: 'Merano',
    race_form: {
      additional_data:
        '{"revealed_race_info":{"track_name":"Merano","state":"ITA","country":"ITA","number":3,"race_name":"2M 1 1/2F Stakes","time":"2024-04-21T13:40:00Z","class":"","start_type":"","prizemonies":null,"rail_position":"","track_direction":"","track_surface":"","group":""}}',
      distance: 3500,
      distance_type: [Object],
      distance_type_id: '570775ae-09ec-42d5-989d-7c8f06366aa7',
      generated: 1,
      silk_base_url: 'drr38safykj6s.cloudfront.net',
    },
    race_id: '85d93672-0b45-47cd-8603-3b3c486f9997',
    race_name: '2M 1 1/2F Stakes',
    race_number: 3,
    venue_country: 'ITA',
    venue_id: '89bbb5e7-6b25-4d38-ae90-ddd5db63718f',
    venue_name: 'Merano',
    venue_state: 'ITA',
  },
];
